# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.SlugField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('used', models.BooleanField()),
                ('phrase', models.ForeignKey(default='%No phrase%', on_delete=django.db.models.deletion.DO_NOTHING, to='board.Phrase')),
            ],
        ),
    ]
